plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.11.0
        checksums:
          darwin-amd64: 656672a3ae9b708c6a37e55872b5c05fb699da03da913e0eda69d5c95dd72d1f
          linux-amd64: 67204d8f6395d689b413890d9cbeaab78af4a7d1c191e58ccd42fd96610c22bd
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.11.0
        checksums:
          darwin-amd64: 5140c4ad8bfcb5cd081669fa951baa9e9c90223e2c4b2eba0cd9e00e778a069c
          linux-amd64: a0277b508c27dd6eefadf0b5a1d261bb21ba8faa4279043cbeecfb0d1cd5c94d
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
