plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.32.0
        checksums:
          darwin-amd64: 999bccacd55614b7a9b6ff890e4df63244d2800530e2006bf50620b55bb7bd22
          linux-amd64: 5a713b84367facf6b36592389a643d4d3103f50ca815ed4d2ecdec0b138140b6
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.34.0
        checksums:
          darwin-amd64: 007c0c920eef87c81fc762ef72bb8eba3a6da38d471ce524674f4ee435de7187
          linux-amd64: e85e1df3a13b6b58719b919a92c12cf7f4b5c9d9afab019e656a38cb65b52e12
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
