plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.29.0
        checksums:
          darwin-amd64: cd7022f92fcc716d441066fe74452f3f417d5f5a93a039fe204e098136ef1b00
          linux-amd64: 7e8257e186f1ce095ac1b0d02458823a3aa987d029eff4ceb515dd8ee77914ed
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.31.0
        checksums:
          darwin-amd64: 8f276015660c126227691cdafb2a2410d9fed449631429650f68d7e253cb3761
          linux-amd64: eaa14146ada31568c14203675b29e72a7399fb05f12213a5f3c629961e4d38d2
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
