plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.12.0
        checksums:
          darwin-amd64: 14d37777669e706f572c53999832db1d3c87ae23c1a3b055d715bd5cd590ca1e
          linux-amd64: c4823263fec1fccaecd89a3e8f3e1bb83c0f9416d5503af423675fb4628a4560
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.14.0
        checksums:
          darwin-amd64: a653ebeaa92a3b4b0efeeddc9b3c8b6c2f40144f80abbebffe6586f567f0dd6f
          linux-amd64: 47c23b17acbc6e3d08428024a0ef617dc2f1d701d72e6c5fe7b711215ec78a00
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
