plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.36.0
        checksums:
          darwin-amd64: 838b9510eec25fce767165649b5abe5caa8bf5fa92a04354db3fbdd7ba76e1e1
          linux-amd64: ef89cc9ccc6ca5822caa8b09ce52ba97a1000a52fbae2d1971bcb06c154986b7
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.38.0
        checksums:
          darwin-amd64: a752036a5a9c7e00f40f8cbacc9b7a9539cd5ad4c8bea2a462148890ac1d5407
          linux-amd64: d407ed2eb3d14ceed09f75562e6948e36f55b759529ead5b0dc33169508c1120
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
