plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.38.0
        checksums:
          darwin-amd64: e260519a5a25621c947c900629a5610cc94776fc113442af3584e5b3402c1d2e
          linux-amd64: 9730041c3fb1388f7ed879a956423bca16e9b821a66d8f3f468e3a5692d1a31d
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.40.0
        checksums:
          darwin-amd64: e29fef2cac0680597653deaa7e5ab904498497ad71fd53346a4ae19c37e929be
          linux-amd64: 6c028e3beac58ce9622f143ffb99cd014ce296e3367f4bfb10e12bccb50d444a
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
