plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.3.1
        checksums:
          darwin-amd64: 862f55ee4383b038fb841441c6a5e986f1746149cca31e74c882abdf44ef354f
          linux-amd64: 5e64768e291873135b569169072565946ddacd12fa56d204d36230142f7558b2
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.3.0
        checksums:
          darwin-amd64: 08a65d8db9555c4580dbf6cdfd954ffafc687ecbf5a71a643bc190baa9b774ad
          linux-amd64: dda61df35df69154836b4f6caa14f88d6b1a59acdb99005e5f5de986fa33f37b
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
