plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-amalgomate-plugin:amalgomate-plugin:1.4.0
        checksums:
          darwin-amd64: feb60f34cd51052234dc4e234c26d4951ba63c7e312979ffe3aecab438214b72
          linux-amd64: bb5f1465084991a2dc3f85a9cc8106a117a9042aa69c0758f87cad5edaf30b69
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.3.0
        checksums:
          darwin-amd64: 08a65d8db9555c4580dbf6cdfd954ffafc687ecbf5a71a643bc190baa9b774ad
          linux-amd64: dda61df35df69154836b4f6caa14f88d6b1a59acdb99005e5f5de986fa33f37b
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - generated_src
  paths:
    - godel
